import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';

import { csvRows, type SourceRecord } from '../../common/csv/parse-csv';
import { buildTemplate } from '../../common/spreadsheet/build-template';
import {
  isDocx,
  isXlsx,
  sheetRecords,
} from '../../common/spreadsheet/read-workbook';
import { PrismaService } from '../../database/prisma.service';
import { Prisma } from '../../generated/prisma/client';
import { UserStatus } from '../auth/auth.types';
import { ImportsService } from '../imports/imports.service';
import { InvitationService } from '../auth/invitation/invitation.service';
import { TeacherScopeService } from '../auth/tenant/teacher-scope.service';
import { TenantContextService } from '../auth/tenant/tenant-context.service';
import { QueryStudentsDto, StudentSort } from './dto/query-students.dto';
import { UpdateStudentDto } from './dto/update-student.dto';

/**
 * Whitelist of roster orderings. A map (rather than building orderBy from the
 * raw query) keeps the sort key from ever reaching Prisma unvalidated.
 */
const STUDENT_ORDER_BY: Record<
  StudentSort,
  Prisma.StudentOrderByWithRelationInput
> = {
  [StudentSort.ROLL_ASC]: { rollNumber: 'asc' },
  [StudentSort.ROLL_DESC]: { rollNumber: 'desc' },
  [StudentSort.NAME_ASC]: { user: { name: 'asc' } },
  [StudentSort.NAME_DESC]: { user: { name: 'desc' } },
  [StudentSort.NEWEST]: { createdAt: 'desc' },
  [StudentSort.OLDEST]: { createdAt: 'asc' },
};

/** Result of a bulk CSV import (§2.10). */
export interface ImportSummary {
  batchId: string;
  batch: string;
  total: number;
  imported: { row: number; name: string; email: string; rollNumber: string }[];
  failed: { row: number; email: string; reason: string }[];
}

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;

/**
 * Header spellings accepted for each required column.
 *
 * Declared once so the header *search* and the value *mapping* cannot disagree
 * — they did briefly, and the result was a file that failed the search, fell
 * back to row 1, and then imported anyway. The canonical name is first.
 */
const NAME_HEADERS = ['name', 'fullname', 'studentname', 'candidatename'];
const EMAIL_HEADERS = ['email', 'e-mail', 'emailaddress', 'emailid', 'mail'];
const MAX_IMPORT_ROWS = 1000;

/**
 * Student management (contract §2.10), scoped to the caller's institute.
 * Students are *created* via the invitation flow; here admins list, view,
 * reassign batch, edit name, and deactivate them. A flattened view joins the
 * academic record (Student) with the auth record (User) and the batch.
 */
@Injectable()
export class StudentsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly tenant: TenantContextService,
    private readonly teacherScope: TeacherScopeService,
    private readonly invitations: InvitationService,
    private readonly imports: ImportsService,
  ) {}

  private instituteId(): string {
    const id = this.tenant.getInstituteId();
    if (!id)
      throw new ForbiddenException('No institute in the current context');
    return id;
  }

  /**
   * The roster template, generated from the same column names the parser reads
   * so the two cannot drift apart.
   */
  importTemplate(): Promise<Buffer> {
    return buildTemplate({
      sheetName: 'Students',
      headers: ['name', 'email'],
      examples: [
        ['Aarav Sharma', 'aarav.sharma@example.com'],
        ['Priya Nair', 'priya.nair@example.com'],
      ],
      notes: [
        'Bulk import students',
        '',
        'Required columns:',
        "name    The candidate's full name, as it should appear on their result.",
        'email   Their email address. It must be unique within your institute —',
        '        the activation link is sent here.',
        '',
        'What happens on import:',
        '1. Each row is invited to the batch you selected in the dialog.',
        '2. A roll number is generated by the platform. Do NOT add a roll-number',
        '   column — one pasted from another list could collide with a candidate',
        '   who already exists.',
        '3. Every student starts as PENDING and becomes ACTIVE once they follow',
        '   the emailed link and set a password.',
        '',
        'Notes:',
        '- Delete the two example rows before uploading.',
        '- Up to 1000 rows per file.',
        '- A row that fails (missing name, invalid email, duplicate) is reported',
        '  with its row number; the rest of the file still imports.',
        '- .csv works too, if you would rather use one.',
      ],
    });
  }

  /**
   * Bulk-import a batch's students from a spreadsheet or CSV (§2.10).
   *
   * Columns: `name`, `email` (required). Roll numbers are always
   * server-generated ({yy}{institute code}{sequence}, §2.11) and never read
   * from the file — letting a spreadsheet set them would let one bad paste
   * collide with an existing candidate's identity.
   *
   * Excel is accepted because that is what schools actually keep their rosters
   * in; asking an office to re-save as CSV is where a bulk import goes wrong
   * (lost leading zeros, mangled encodings, the wrong delimiter for the
   * machine's locale). Both formats land on one set of records so the two
   * paths cannot drift apart.
   *
   * Each row is created through the normal invitation flow (PENDING → email
   * link → set password). Processing is per-row and fault-tolerant: a bad row
   * is reported in `failed` without aborting the rest.
   */
  async importRoster(params: {
    batchId: string;
    buffer: Buffer;
    invitedById: string;
    /** Original upload name, recorded in the import history. */
    fileName?: string;
  }): Promise<ImportSummary> {
    const instituteId = this.instituteId();
    const batch = await this.prisma.batch.findFirst({
      where: { id: params.batchId, instituteId },
      select: { id: true, name: true },
    });
    if (!batch) {
      throw new BadRequestException('Batch not found in your institute');
    }

    const spreadsheet = isXlsx(params.buffer);

    /**
     * Say what the file actually is before trying to read it as text.
     *
     * Anything that is not a workbook was previously assumed to be CSV, so a
     * Word document or a PDF was decoded as UTF-8 and reported as "the CSV has
     * no data rows" — which is both untrue and useless, since the fix is to
     * upload a different file rather than to add rows to this one.
     */
    if (!spreadsheet) {
      if (isDocx(params.buffer)) {
        throw new BadRequestException(
          'That is a Word document. Student rosters are imported from an ' +
            'Excel workbook (.xlsx) or a CSV — download the template to see ' +
            'the columns.',
        );
      }
      const looksBinary =
        params.buffer.subarray(0, 4096).includes(0) ||
        (params.buffer[0] === 0x50 && params.buffer[1] === 0x4b);
      if (looksBinary) {
        throw new BadRequestException(
          'That file is not a spreadsheet or a CSV. Upload an .xlsx ' +
            'workbook or a .csv file — download the template to see the ' +
            'columns.',
        );
      }
    }

    const kind = spreadsheet ? 'sheet' : 'CSV';
    let records: SourceRecord[];
    try {
      records = spreadsheet
        ? await sheetRecords(params.buffer, {
            // Find the table rather than assuming A1: real rosters have a
            // title row above the headers, or sit on a later tab.
            required: [
              'name|fullname|studentname',
              'email|e-mail|emailaddress',
            ],
            // One more than the cap, so an oversized file is rejected by the
            // check below instead of being read entirely into memory first.
            maxRows: MAX_IMPORT_ROWS + 1,
          })
        : csvRows(params.buffer.toString('utf8'));
    } catch (err) {
      // The format was identified from the file's own bytes, so this is a real
      // workbook that is damaged — truncated download, half-written export.
      // Without this the uploader gets an opaque 500 for a problem that is
      // entirely on their side and trivially fixable.
      throw new BadRequestException(
        'That file could not be read — it looks damaged or incomplete. Open ' +
          'it, re-save it, and upload it again. ' +
          `(${err instanceof Error ? err.message : 'unreadable'})`,
      );
    }

    if (records.length === 0) {
      throw new BadRequestException(
        `The ${kind} has no data rows. The first row must be the column ` +
          'headers, with the students beneath it.',
      );
    }
    if (records.length > MAX_IMPORT_ROWS) {
      throw new BadRequestException(
        `Import is limited to ${MAX_IMPORT_ROWS} rows at a time`,
      );
    }
    /**
     * Check the columns BEFORE normalising the aliases.
     *
     * The check has to read the headers the file actually has: mapping first
     * would create empty `name`/`email` keys on every row, so a sheet of
     * completely unrelated columns would pass the guard and then fail row by
     * row with "Missing name". On a 500-row file that is 500 useless errors
     * instead of one sentence naming the real problem.
     */
    const headers = new Set(Object.keys(records[0].data));
    const hasName = NAME_HEADERS.some((h) => headers.has(h));
    const hasEmail = EMAIL_HEADERS.some((h) => headers.has(h));
    if (!hasName || !hasEmail) {
      const missing = [
        ...(hasName ? [] : ['name']),
        ...(hasEmail ? [] : ['email']),
      ];
      throw new BadRequestException(
        `The ${kind} is missing the ${missing.join(' and ')} column` +
          `${missing.length > 1 ? 's' : ''}. Found: ` +
          `${[...headers].join(', ') || '(no headers)'}. ` +
          'Download the template to see the expected columns.',
      );
    }

    // Only now fold the accepted spellings onto the canonical keys — "Full
    // Name" and "E-Mail" are the same intent, and failing them helps nobody.
    const firstOf = (row: Record<string, string>, keys: string[]) =>
      keys.map((k) => row[k]).find((v) => v) ?? '';
    for (const { data } of records) {
      if (!data.name) data.name = firstOf(data, NAME_HEADERS);
      if (!data.email) data.email = firstOf(data, EMAIL_HEADERS);
    }

    const seenEmails = new Set<string>();
    const imported: ImportSummary['imported'] = [];
    const failed: ImportSummary['failed'] = [];

    for (const { row: rowNum, data: rec } of records) {
      // The real row in the user's file, not a running count: the header is
      // not always row 1 and blank rows are skipped, so a computed position
      // would send them to the wrong line when they went to fix it.
      const name = rec.name;
      const email = rec.email.toLowerCase();
      try {
        if (!name) throw new Error('Missing name');
        if (!EMAIL_RE.test(email)) throw new Error('Invalid email');
        if (seenEmails.has(email)) {
          throw new Error('Duplicate email in file');
        }

        // inviteStudent() generates the roll number itself and, row-by-row
        // sequential awaiting here, always sees every prior row's write —
        // no risk of two rows in the same file computing the same one.
        const invited = await this.invitations.inviteStudent(
          instituteId,
          params.invitedById,
          { name, email, batchId: batch.id },
        );

        seenEmails.add(email);
        imported.push({
          row: rowNum,
          name,
          email,
          rollNumber: invited.rollNumber ?? '',
        });
      } catch (err) {
        failed.push({
          row: rowNum,
          email,
          reason: err instanceof Error ? err.message : 'Failed',
        });
      }
    }

    // Best-effort history: never let logging fail an import that succeeded.
    await this.imports.record({
      kind: 'STUDENTS_CSV',
      fileName:
        params.fileName ?? (spreadsheet ? 'students.xlsx' : 'students.csv'),
      total: records.length,
      imported: imported.length,
      failures: failed,
      target: `Batch: ${batch.name}`,
    });

    return {
      batchId: batch.id,
      batch: batch.name,
      total: records.length,
      imported,
      failed,
    };
  }

  /**
   * Roster listing — always paginated. An institute's roll can run to thousands
   * of students (they are bulk-imported by CSV), so an uncapped findMany would
   * serialise the entire roll into a single response.
   */
  async findAll(query: QueryStudentsDto) {
    const scope = await this.teacherScope.myBatchIds();
    // Intersect the caller's own batch filter (if any) with their teacher
    // scope (if any) rather than letting both conditions collide on the same
    // field — a batch outside scope yields an empty page, not a 500.
    const effectiveBatchIds =
      scope === null
        ? query.batchId
          ? [query.batchId]
          : undefined
        : query.batchId
          ? scope.includes(query.batchId)
            ? [query.batchId]
            : []
          : scope;

    const search = query.search?.trim();

    const where: Prisma.StudentWhereInput = {
      instituteId: this.instituteId(),
      ...(effectiveBatchIds && { batchId: { in: effectiveBatchIds } }),
      // Class/program narrow through the batch's parent chain, so the caller
      // never has to know which batches belong to which class.
      ...(query.classId && { batch: { classId: query.classId } }),
      ...(query.programId && {
        batch: { class: { programId: query.programId } },
      }),
      ...(query.status && { user: { status: query.status } }),
      // Roll number lives on Student; name/email on the related User. `mode:
      // insensitive` keeps this usable for a human typing a partial name.
      ...(search && {
        OR: [
          { rollNumber: { contains: search, mode: 'insensitive' as const } },
          {
            user: { name: { contains: search, mode: 'insensitive' as const } },
          },
          {
            user: { email: { contains: search, mode: 'insensitive' as const } },
          },
        ],
      }),
    };
    const take = Math.min(query.limit ?? 50, 200);
    const skip = query.offset ?? 0;

    const orderBy = STUDENT_ORDER_BY[query.sort ?? StudentSort.ROLL_ASC];

    /**
     * Status tallies for the roster's cards and tabs.
     *
     * Counted server-side over the WHOLE filtered set. The client used to tally
     * statuses across the loaded page only, which silently understated every
     * figure for an institute with more students than one page (the API caps a
     * page at 200). `countsWhere` drops the status filter itself so each tab
     * keeps showing its own total while another tab is selected.
     */
    const countsWhere: Prisma.StudentWhereInput = { ...where, user: undefined };
    const withStatus = (status: UserStatus): Prisma.StudentWhereInput => ({
      ...countsWhere,
      // Preserve any search term, which also constrains `user`.
      user: search
        ? {
            status,
            OR: [
              { name: { contains: search, mode: 'insensitive' } },
              { email: { contains: search, mode: 'insensitive' } },
            ],
          }
        : { status },
    });

    const [
      students,
      total,
      allCount,
      activeCount,
      disabledCount,
      pendingCount,
    ] = await this.prisma.$transaction([
      this.prisma.student.findMany({
        where,
        select: {
          id: true,
          rollNumber: true,
          createdAt: true,
          user: { select: { name: true, email: true, status: true } },
          batch: { select: { id: true, name: true } },
        },
        orderBy,
        take,
        skip,
      }),
      this.prisma.student.count({ where }),
      this.prisma.student.count({ where: countsWhere }),
      this.prisma.student.count({ where: withStatus(UserStatus.ACTIVE) }),
      this.prisma.student.count({ where: withStatus(UserStatus.DISABLED) }),
      this.prisma.student.count({ where: withStatus(UserStatus.PENDING) }),
    ]);

    return {
      items: students.map((s) => ({
        id: s.id,
        rollNumber: s.rollNumber,
        name: s.user.name,
        email: s.user.email,
        status: s.user.status,
        batch: s.batch,
        createdAt: s.createdAt,
      })),
      total,
      limit: take,
      offset: skip,
      /** Whole-set tallies — see the `countsWhere` comment above. */
      counts: {
        all: allCount,
        active: activeCount,
        disabled: disabledCount,
        pending: pendingCount,
      },
    };
  }

  async findOne(id: string) {
    const scope = await this.teacherScope.myBatchIds();
    const s = await this.prisma.student.findFirst({
      where: {
        id,
        instituteId: this.instituteId(),
        ...(scope && { batchId: { in: scope } }),
      },
      select: {
        id: true,
        rollNumber: true,
        createdAt: true,
        user: { select: { name: true, email: true, status: true } },
        batch: { select: { id: true, name: true } },
      },
    });
    if (!s) throw new NotFoundException('Student not found');
    return {
      id: s.id,
      rollNumber: s.rollNumber,
      name: s.user.name,
      email: s.user.email,
      status: s.user.status,
      batch: s.batch,
      createdAt: s.createdAt,
    };
  }

  async update(id: string, dto: UpdateStudentDto) {
    const owned = await this.getOwned(id);

    if (dto.batchId !== undefined && dto.batchId !== owned.batchId) {
      const batch = await this.prisma.batch.findFirst({
        where: { id: dto.batchId, instituteId: this.instituteId() },
      });
      if (!batch) {
        throw new BadRequestException('Batch not found in your institute');
      }
    }

    await this.prisma.$transaction(async (tx) => {
      if (dto.name !== undefined) {
        await tx.user.update({
          where: { id: owned.userId },
          data: { name: dto.name },
        });
      }
      if (dto.batchId !== undefined) {
        await tx.student.update({
          where: { id },
          data: { batchId: dto.batchId },
        });
      }
    });

    return this.findOne(id);
  }

  /** Soft-delete: disables the student's account (contract §2.10 "delete"). */
  async deactivate(id: string) {
    const owned = await this.getOwned(id);
    await this.prisma.user.update({
      where: { id: owned.userId },
      data: { status: UserStatus.DISABLED },
    });
    return this.findOne(id);
  }

  /** Undoes a deactivation. Refuses a PENDING/ACTIVE student — there is no
   * disabled state to lift, so "reactivate" would be a confusing no-op. */
  async reactivate(id: string) {
    const owned = await this.getOwned(id);
    const user = await this.prisma.user.findUniqueOrThrow({
      where: { id: owned.userId },
      select: { status: true },
    });
    if (user.status !== UserStatus.DISABLED) {
      throw new BadRequestException(
        'Only a deactivated student can be reactivated',
      );
    }
    await this.prisma.user.update({
      where: { id: owned.userId },
      data: { status: UserStatus.ACTIVE },
    });
    return this.findOne(id);
  }

  /** Re-sends the activation email for a student still awaiting one. */
  async resendInvite(id: string) {
    const owned = await this.getOwned(id);
    await this.invitations.resendInvite(owned.userId, this.instituteId());
    return this.findOne(id);
  }

  private async getOwned(id: string) {
    const student = await this.prisma.student.findFirst({
      where: { id, instituteId: this.instituteId() },
      select: { id: true, userId: true, batchId: true },
    });
    if (!student) throw new NotFoundException('Student not found');
    return student;
  }
}
