import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

import { Injectable, Logger } from '@nestjs/common';

import { MediaStoragePort, StoredObject } from '../ports/media-storage.port';

/**
 * Filesystem media storage — the development fallback.
 *
 * Infrastructure is the client's responsibility (§4/§14), so the platform must
 * run before an S3 bucket exists. Keys are shaped exactly like the S3 adapter's
 * so switching backends needs no data migration beyond copying the objects.
 *
 * Not for production: the files live on the API's own disk, which does not
 * survive a redeploy on Render/Vercel-style hosting.
 */
@Injectable()
export class LocalMediaAdapter extends MediaStoragePort {
  readonly name = 'local-filesystem';
  private readonly logger = new Logger(LocalMediaAdapter.name);
  private readonly root = resolve(process.cwd(), 'storage', 'media');

  constructor() {
    super();
    this.logger.warn(
      'Media is on local disk — set AWS_S3_BUCKET (+ credentials) for durable storage.',
    );
  }

  private path(key: string): string {
    // Keys are generated by us; still refuse anything that climbs out.
    const full = resolve(this.root, key);
    if (!full.startsWith(this.root)) throw new Error('Invalid media key');
    return full;
  }

  async put(params: {
    instituteId: string;
    fileName: string;
    mimeType: string;
    body: Buffer;
  }): Promise<StoredObject> {
    const ext = params.fileName.includes('.')
      ? params.fileName.slice(params.fileName.lastIndexOf('.'))
      : '';
    const key = `${params.instituteId}/${randomUUID()}${ext}`;
    const file = this.path(key);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, params.body);
    return { key };
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.path(key));
    } catch {
      return null;
    }
  }

  async remove(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }

  /** No CDN in front of local disk — the API streams these itself. */
  publicUrl(): string | null {
    return null;
  }
}

/** Exported for tests that need the on-disk location. */
export const localMediaRoot = () => join(process.cwd(), 'storage', 'media');
